unsorted = [
    "American - Southern",
    "American - Southwestern",
    "American - Cajun/Creole",
    "American - California",
    "Mexican",
    "Latin (Not Mexican)",
    "Caribbean",
    "French",
    "Italian",
    "German",
    "Nordic",
    "Russian",
    "Polish",
    "Czech",
    "Greek",
    "Turkish",
    "British & Irish",
    "Chinese",
    "Japanese",
    "Korean",
    "Thai",
    "Burmese",
    "Indian",
    "Pakistani",
    "Nepalese",
    "Afghani",
    "North African",
    "East African",
    "West African",
    "South African",
    "Persian",
    "Israeli",
    "Comfort Food",
    "Quick and Easy",
    "Street Food",
]
